### ISSUE TITLE
Add the "version" info" + "Documentation" and "Report A Bug" buttons (in bl_info)

### ISSUE THREAD

**Issue by xan2622** [proxeIO/pipe-nightmare#1]
Hi.

In the bl_info paragraph of your __ init __ .py python file, could you please add these three lines?

"version": (0.3.33),
"wiki_url": "https://blenderartists.org/t/pipe-nightmare-0-3-33/682448",
"tracker_url: "https://github.com/proxeIO/pipenightmare/issues",

These are just example URLs, feel free to use the links of your choice.

It will display the version of your addon (that is currently missing) and it will also add two new buttons in the Preferences > Addon details.

<img width="890" alt="Documentation_ReportABug" src="https://user-images.githubusercontent.com/1732773/59555523-f5f67b00-8fb3-11e9-8e7b-117ec28a72e3.png">

I think these buttons can be useful for users.
Thank you.

**Comment by proxeIO** [comment]
![image](https://user-images.githubusercontent.com/13005588/67631566-328d8980-f866-11e9-8aa2-ecaa8dcae415.png)
Have the version number, wiki url and tracker url may not be a bad idea, however I tend to include them around version 0.5 just to keep issues low while it's in early stages of development.

Also working on a read the docs repo that should help with documentation and FAQ's, however boxcutter currently has me tied down lol.
