### ISSUE TITLE
Curves are not having any depth in 2.9

### ISSUE THREAD

**Issue by MangoDev232** [proxeIO/pipe-nightmare#2]
Hey ProxelO,
the curent build has unfortunately no depth. I'm having only curves with zero depth. Its really anoying to add this manualy. I would love to see an updated version of the addon beacause its very handy for me.
Thank you

**Comment by Seitekful** [comment]
Switching to "Object" in each of the pipes Curve Properties>Geometry>Bevel fixes this. (Can be done for all while holding alt). Just for the moment this is a workaround

**Comment by MangoDev232** [comment]
Thanks, thats allright.
